
from .app_imagem import AppImagemViewSet, AppImagemDetailView, AppImagemListView, AppImagemUpdateView, AppImagemCreateView, AppImagemDeleteView
from .aplicativo import AplicativoModelViewSet, AplicativoModelDetailView, AplicativoModelListView, AplicativoModelUpdateView, AplicativoModelCreateView, AplicativoModelDeleteView