# Generated by Django 4.0.4 on 2022-05-19 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTopicModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='Última modificacao')),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('isPublic', models.BooleanField(default=False, null=True)),
                ('isRemoved', models.BooleanField(default=False, null=True)),
                ('nome_do_topico', models.CharField(help_text='O nome deve ser uma palavra apenas', max_length=64, verbose_name='Nome do tópico')),
                ('icone_do_topico', models.ImageField(help_text='Icone será mostrado ao receber a notificação, se suportado pelo celular', upload_to='icones/topicos/', verbose_name='Icone do tópico')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationtopicmodel_criados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationtopicmodel_modificados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('removido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationtopicmodel_removidos_por_mim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topico',
                'verbose_name_plural': 'Topicos',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='Última modificacao')),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('isPublic', models.BooleanField(default=False, null=True)),
                ('isRemoved', models.BooleanField(default=False, null=True)),
                ('notification_token', models.CharField(max_length=512, verbose_name='Token de app')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationtokenmodel_criados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationtokenmodel_modificados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('removido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationtokenmodel_removidos_por_mim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token registrado',
                'verbose_name_plural': 'Tokens registrados',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='Data de criação')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='Última modificacao')),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('isPublic', models.BooleanField(default=False, null=True)),
                ('isRemoved', models.BooleanField(default=False, null=True)),
                ('titulo_da_notificacao', models.CharField(max_length=128, verbose_name='Titulo da notificação')),
                ('mensagem_da_notificacao', models.CharField(help_text='A mensagem deve ser curta, não mais do que 256 carateres, o ideal é até 128', max_length=256, verbose_name='Mensagem para enviar')),
                ('icone_da_notificacao', models.ImageField(help_text='Icone será mostrado ao receber a notificação, se suportado pelo celular', upload_to='icones/topicos/', verbose_name='Icone da notificação')),
                ('processing_started', models.BooleanField(default=False)),
                ('processing_is_done', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationmodel_criados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='notifications_desse_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Motoristas que devem receber essa notificação')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationmodel_modificados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('removido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificationmodel_removidos_por_mim', to=settings.AUTH_USER_MODEL)),
                ('topicos', models.ManyToManyField(blank=True, help_text='Selecione os topicos caso queira enviar para todos', related_name='notifications_nesse_topico', to='notifications.notificationtopicmodel', verbose_name='Tópicos da notificação')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
