# Generated by Django 4.0.4 on 2022-05-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationmodel',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='DT. cadastro'),
        ),
        migrations.AlterField(
            model_name='notificationmodel',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='DT. Atualização'),
        ),
        migrations.AlterField(
            model_name='notificationtokenmodel',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='DT. cadastro'),
        ),
        migrations.AlterField(
            model_name='notificationtokenmodel',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='DT. Atualização'),
        ),
        migrations.AlterField(
            model_name='notificationtopicmodel',
            name='created',
            field=models.DateTimeField(auto_now=True, verbose_name='DT. cadastro'),
        ),
        migrations.AlterField(
            model_name='notificationtopicmodel',
            name='lastModified',
            field=models.DateTimeField(auto_now=True, verbose_name='DT. Atualização'),
        ),
    ]
