# Generated by Django 4.0.4 on 2022-06-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationmodel_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='destinatarios',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='icone_da_notificacao',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='topicos',
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
    ]
