# Generated by Django 4.0.4 on 2022-06-29 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notificationmodel_destinatarios_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationmodel',
            name='mensagem_da_notificacao',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='titulo_da_notificacao',
        ),
    ]
