# Generated by Django 4.0.4 on 2022-05-29 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacoes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='DT. cadastro')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='DT. Atualização')),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('isPublic', models.BooleanField(default=False, null=True)),
                ('isRemoved', models.BooleanField(default=False, null=True)),
                ('descricao_da_imagem', models.CharField(max_length=126, verbose_name='Descrição da imagem')),
                ('imagem', models.ImageField(upload_to='apps/imagens/')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appimagem_criados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appimagem_modificados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('removido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appimagem_removidos_por_mim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagem',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AplicativoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='DT. cadastro')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='DT. Atualização')),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('isPublic', models.BooleanField(default=False, null=True)),
                ('isRemoved', models.BooleanField(default=False, null=True)),
                ('nome_do_app', models.CharField(max_length=512, verbose_name='Nome o app')),
                ('url_termos_de_uso', models.URLField(max_length=512, verbose_name='Url dos termos de uso ao app')),
                ('url_politica_de_privacidade', models.URLField(max_length=512, verbose_name='Url da politica de privicade do app')),
                ('url_fale_conosco', models.URLField(max_length=512, verbose_name='Url do SAC')),
                ('url_da_ajuda', models.URLField(max_length=512, verbose_name='Url do FAQ')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicativomodel_criados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('imagem_background_login', models.ForeignKey(blank=True, help_text='Imagem de fundo no login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_de_login', to='aplicativos.appimagem')),
                ('imagem_background_recuperar_senha', models.ForeignKey(blank=True, help_text='Imagem de fundo na recuperação de senha', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagens_de_recuperar_senha', to='aplicativos.appimagem')),
                ('imagens_de_capa', models.ManyToManyField(related_name='apps_usando_essa_imagem', to='aplicativos.appimagem')),
                ('logotipo_do_app', models.ForeignKey(blank=True, help_text='Icone do app', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logotipos', to='aplicativos.appimagem')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicativomodel_modificados_por_mim', to=settings.AUTH_USER_MODEL)),
                ('organizacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lista_de_aplicativos_dessa_organizacao', to='organizacoes.organizacao')),
                ('removido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aplicativomodel_removidos_por_mim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplicativo',
                'verbose_name_plural': 'Aplicativo',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
