# Generated by Django 4.0.4 on 2022-07-01 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='DT. cadastro')),
                ('lastModified', models.DateTimeField(auto_now=True, verbose_name='DT. Atualização')),
                ('isActive', models.BooleanField(default=True, null=True)),
                ('isPublic', models.BooleanField(default=False, null=True)),
                ('isRemoved', models.BooleanField(default=False, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertamodel_criado_por_mim', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertamodel_modificado_por_mim', to=settings.AUTH_USER_MODEL)),
                ('removido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertamodel_removido_por_mim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alerta',
                'ordering': ['created'],
                'abstract': False,
            },
        ),
    ]
